### ISSUE TITLE
Results about CMeKGCrawler

### ISSUE THREAD

**Issue by Yaozuwu** [huyuanxin/CMeKGCrawler#1]
I would like to ask, is the data crawled by the crawler to build the knowledge graph in the form of a triplet?

**Comment by huyuanxin** [comment]
看了你的头像，猜测你跟我一样是中国人，就用中文交流吧。
如果你问的是三元组（实体-关系-实体），那么这个爬虫会爬取数据并自动构建三元组到图形数据库（项目使用的是Neo4j）中。
整个过程如下：
* 爬取数据
* 数据保存到json
* 存储实体
* 建立关系
爬取的数据有脏数据，需要自行处理。
具体是使用请参考[这个项目--后端](https://github.com/huyuanxin/MKGS)和[这个项目-前端](https://github.com/huyuanxin/MKGS_FE)。这个是我的毕业设计，请注意版权
